require('autocmd.highlight_match')
-- require('autocmd.conditional_wrap_text')
require('autocmd.autosave')
require('autocmd.remove_white_space')
require('autocmd.auto_cursor_shape')
require('autocmd.clear_search')
require('autocmd.set_filetype')
-- require('autocmd.clear_jump')
require('autocmd.reset_cursor')
require('autocmd.markdown_conceal')
require('autocmd.markdown_codeblock')
require('autocmd.markdown_rules')
