-- https://github.com/LazyVim/LazyVim/blob/879e29504d43e9f178d967ecc34d482f902e5a91/lua/lazyvim/config/init.lua#L31

return {
	Array = ' ',
	Boolean = ' ',
	Class = ' ',
	Codeium = '󰘦 ',
	Color = ' ',
	Control = ' ',
	Collapsed = ' ',
	Constant = '󰏿 ',
	Constructor = ' ',
	Copilot = ' ',
	Enum = ' ',
	EnumMember = ' ',
	Event = ' ',
	Field = ' ',
	File = ' ',
	Folder = ' ',
	Function = '󰊕 ',
	Interface = ' ',
	Key = ' ',
	Keyword = ' ',
	Method = '󰊕 ',
	Module = ' ',
	Namespace = '󰦮 ',
	Null = ' ',
	Number = '󰎠 ',
	Object = ' ',
	Operator = ' ',
	Package = ' ',
	Property = ' ',
	Reference = ' ',
	Snippet = ' ',
	String = ' ',
	Struct = '󰆼 ',
	TabNine = '󰏚 ',
	Text = ' ',
	TypeParameter = ' ',
	Unit = ' ',
	Value = ' ',
	Variable = '󰀫 ',
}
